name: "Bug Report"
description: "File a bug report."
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ChinoCodeDemon
body:
  - type: textarea
    attributes:
      id: what-happened
      label: What went wrong?
      description: Please describe what went wrong and how it happened.
    validations:
      required: true
  - type: textarea
    attributes:
      id: bot-response
      label: Bot Response.
      description: Please paste or describe the bots response as accurate as possible.
  - type: markdown
    attributes:
      value: "Thanks for completing this form. This will help to improve the bot further."