name: "Bug Report for selfhosted instances"
description: "File a bug report your selfhosted instances."
title: "[Bug-Selfhosted]: "
labels: ["bug", "selfhosted"]
assignees:
  - ChinoCodeDemon
body:
  - type: textarea
    attributes:
      id: what-happened
      label: What went wrong?
      description: Please describe what went wrong and how it happened.
    validations:
      required: true
  - type: textarea
    attributes:
      id: bot-response
      label: Bot Response.
      description: Please paste or describe the bots response as accurate as possible.
  - type: input
    attributes:
      label: Python Version
      description: What python version are you running?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: What operating system are you using for your instance.
      multiple: false
      options:
      - Windows
      - Linux
      - MacOS
      - BSD
  - type: textarea
    attributes:
      id: how-to-replicate
      label: How to replicate the bug
      description: Please describe how to replicate your problem.
  - type: markdown
    attributes:
      value: "Thanks for completing this form. This will help to improve the bot further."